name: curl-ijohnson
version: "0.1"
summary: test strict snap of cURL
base: core20
description: |
  cURL is a command line tool and library for transferring data with URLs.

grade: stable
confinement: strict

apps:
  curl:
    command: usr/bin/curl
    plugs:
      - home
      - removable-media
      - network
      - network-bind

parts:
  curl:
    plugin: nil
    stage-packages: [curl]
